---
services:
  myapp:
    container_name: application-cont
    image: appimage
    ports:
      - "1112:8080"
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 100M
        limits:
          cpus: "1.0"
          memory: 1500M
    depends_on:
      - devopsdb
    networks:
      - mynetwork

  devopsdb:
    container_name: devopsdb
    image: dbimage
    ports:
      - "1113:3306"
    volumes:
      - userdata:/var/lib/mysql
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 100M
        limits:
          cpus: "1.0"
          memory: 200M
    environment:
      MYSQL_ROOT_PASSWORD: "devopspassword"
    networks:
      - mynetwork
volumes:
  userdata:
networks:
  mynetwork:
    driver: overlay
               
