---
services:
  myapp:
    container_name: application-cont
    image: maneesha3/webapp:v1
    ports:
      - "1112:8080"
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 100M
        limits:
          cpus: "1.0"
          memory: 1500M
    depends_on:
      - devopsdb

  devopsdb:
    container_name: devopsdb
    image: maneesha3/dbimage:webapp
    ports:
      - "1113:3306"
    volumes:
      - userdata:/var/lib/mysql
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 100M
        limits:
          cpus: "1.0"
          memory: 200M
    environment:
      MYSQL_ROOT_PASSWORD: "devopspassword"

volumes:
  userdata:
               
